#lang scheme

(define (make-account balance initial-password)
  (define wrong-attempt-count 0)
  (define (withdraw amount)
    (set! wrong-attempt-count 0)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! wrong-attempt-count 0)
    (set! balance (+ balance amount))
    balance)
  (define (handle-bad-password amount)
    (set! wrong-attempt-count (+ wrong-attempt-count 1))
    (if (= 7 wrong-attempt-count)
        (call-the-cops)
        "Incorrect password"))
  (define (call-the-cops)
    (error "The police is here"))
  (define (dispatch password m)
    (cond ((not (eq? password initial-password)) handle-bad-password)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request" m))))
  dispatch)

(define a (make-account 5 'morituri))

((a 'morituri 'deposit) 5)
((a 'morituri 'withdraw) 10)
((a 'wrong 'deposit) 5)
((a 'wrong 'deposit) 5)
((a 'wrong 'deposit) 5)
((a 'wrong 'deposit) 5)
((a 'wrong 'deposit) 5)
((a 'wrong 'deposit) 5)
((a 'wrong 'deposit) 5)

